version: "3.7"

services:
  docker-fastapi:
    container_name: "docker-fastapi"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: lmcyber/stud_camp/backend:0.1

    ports:
      - 8080:8080

  nginx:
    container_name: "proxy-app"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: lmcyber/stud_camp/nginx:0.1

    ports:
      - 80:80
    depends_on:
      - docker-fastapi

